P_WIFI_R=0
P_WIFI_G=1
P_WIFI_B=2
P_MEAS_R=3
P_MEAS_G=4
P_MEAS_B=11
P_WIFI_BTN=5
P_MEAS_BTN=6

gpio.mode(P_WIFI_BTN,gpio.INT,gpio.PULLUP)
gpio.mode(P_MEAS_BTN,gpio.INPUT,gpio.PULLUP)
gpio.mode(7,gpio.INPUT)
gpio.mode(8,gpio.OUTPUT)
gpio.write(8,gpio.HIGH)
gpio.mode(P_WIFI_R,gpio.OUTPUT)
gpio.mode(P_WIFI_G,gpio.OUTPUT)
gpio.mode(P_WIFI_B,gpio.OUTPUT)
gpio.write(P_WIFI_R,gpio.HIGH)
gpio.write(P_WIFI_G,gpio.HIGH)
gpio.write(P_WIFI_B,gpio.HIGH)
gpio.mode(P_MEAS_R,gpio.OUTPUT)
gpio.mode(P_MEAS_G,gpio.OUTPUT)
gpio.mode(P_MEAS_B,gpio.OUTPUT)
gpio.write(P_MEAS_R,gpio.HIGH)
gpio.write(P_MEAS_G,gpio.HIGH)
gpio.write(P_MEAS_B,gpio.HIGH)
